# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Pin.destroy_all
Board.destroy_all
User.destroy_all

User.create!(username: "daniel",password: "password",
image_url: "http://res.cloudinary.com/pinitt/image/upload/c_thumb,g_face,h_629,w_629/v1473100945/daniel-radcliffe_twr4u1.jpg",
description: "I'm not clumsy, I'm accident-prone!\n
I think I'm a tiny bit like Harry 'cos I'd like to have an owl. Yeah, that's the tiny bit, actually.\n
I'm not a religious person. My mom was of Jewish blood and my dad was Protestant.")

User.create!(username: "emma",password: "password",
image_url: "http://res.cloudinary.com/pinitt/image/upload/c_thumb,h_300,w_300/v1473100256/emma-watson_mblx3y.jpg",
description: "")

User.create!(username: "george",password: "password",
image_url: "http://res.cloudinary.com/pinitt/image/upload/v1473100255/george-clooney_sdydbh.jpg",
description: "I am an American actor, filmmaker, and activist. He has received three Golden Globe Awards for his work as an actor and two Academy Awards, one for acting and the other for producing.")

User.create!(username: "will",password: "password",
image_url: "http://res.cloudinary.com/pinitt/image/upload/c_thumb,h_300,w_300/v1473100255/will-smith_c69qwg.jpg",
description: "I am an American actor, producer, rapper, and songwriter. In April 2007, Newsweek called me the most powerful actor in Hollywood.")

User.create!(username: "taylor",password: "password",
image_url: "http://res.cloudinary.com/pinitt/image/upload/v1473100255/taylor-swift_xzggox.jpg",
description: "I am an American singer-songwriter. Raised in Wyomissing, Pennsylvania, she moved to Nashville, Tennessee, at the age of 14 to pursue a career in country music.")

User.create!(username: "matt",password: "password",
image_url: "http://res.cloudinary.com/pinitt/image/upload/c_thumb,w_300/v1473100255/matt-damon_cufrih.jpg",
description: "I am an American actor, film producer and screenwriter, ranked among Forbes magazine's most bankable stars and is one of the highest-grossing actors of all time.")

User.create!(username: "angelina",password: "password",
image_url: "http://res.cloudinary.com/pinitt/image/upload/c_thumb,h_301,w_301/v1473100849/angelina-jolie_hdam3c.jpg",
description: "I am an American actress, filmmaker, and humanitarian. She has received an Academy Award, two Screen Actors Guild Awards, and three Golden Globe Awards, and has been cited as Hollywood's highest-paid actress.")

User.create!(username: "kerry",password: "password",
image_url: "http://res.cloudinary.com/pinitt/image/upload/c_thumb,h_474,w_474/v1473100849/kerry-washington_kls9g0.jpg",
description: "I am an American actress.
Since 2012, gained wide public recognition for starring in
the ABC drama Scandal, a Shonda Rhimes series in which as Olivia Pope.")




Board.create!(title: "Awesome Food", description: "Yum yum yum...", user_id: 1)
Board.create!(title: "Travel", description: "Let's go somewhere!", user_id: 1)
Board.create!(title: "Cute!", description: "Pets in the door.", user_id: 2)
Board.create!(title: "Celebrities around me", description: "My friends lol", user_id: 2)
Board.create!(title: "Photography", description: "Nice photos with the best camera", user_id: 3)
Board.create!(title: "Design", description: "Check out some designs.", user_id: 4)
Board.create!(title: "Film, music and books", description: "All the stuffs", user_id: 5)
Board.create!(title: "Sports", description: "Sports", user_id: 6)
Board.create!(title: "Technology", description: "Geek", user_id: 7)
Board.create!(title: "Home decor", description: "Decor time.", user_id: 8)

Pin.create!(title: "Pesto Zucchini Noodles", description: "It's time for another summery zucchini recipe and this time it's fresh pesto zucchini noodles with roasted tomatoes and grilled chicken! Ever since I came across the idea of zucchini noodles I have been a little obsessed with them! I mean what's not to like about them? They behave just like spaghetti noodles and they are lighter and healthier! This recipe could not be easier, you simply roast the tomatoes, grill the chicken, slice the zucchini into noodles and then toss it all in a fresh homemade basil pesto! In addition to being nice and light and healthy, this dish is pure summer in a bowl with the juicy roasted tomatoes bursting in your mouth balancing off the creamy pesto. The zucchini noodles can be served cool making this dish perfect for hot summer days!", image_url: "https://s-media-cache-ak0.pinimg.com/236x/cc/1f/7a/cc1f7ad4dc9c8c80fbf58ccff4b086fb.jpg", url:"http://www.closetcooking.com/2015/08/pesto-zucchini-noodles-with-roasted.html", user_id: 1, board_id: 1)
Pin.create!(title: "One Pan Chicken Apple Sausage Pasta", description: "Sooooo good!!", image_url: "https://s-media-cache-ak0.pinimg.com/564x/26/3b/35/263b350447be9fef088d48b3371f025a.jpg", url: "http://inspiredbycharm.com/2014/09/one-pan-chicken-apple-sausage-pasta.html", user_id: 1, board_id: 1)
Pin.create!(title: "Great Dane Puppy", description: "luv him", image_url: "https://s-media-cache-ak0.pinimg.com/564x/34/f3/00/34f30011aef16e6980db07ee691e2083.jpg", url: "http://imgfave.com/view/3650239?utm_source=feedly&utm_medium=feed&utm_campaign=Feed%3A+imgfave%2Fpopular+%28imgfave+%7C+popular%29", user_id: 2, board_id: 3)
Pin.create!(title: "Just For Laughs Newsletter", description: "10 Surprising Facts That'll Make You Feel Young", image_url: "https://s-media-cache-ak0.pinimg.com/564x/24/1f/61/241f61d93c337bc28f343952f1243e89.jpg", url: "http://us2.campaign-archive2.com/?u=c7e478ddf0b14a52394ec553f&id=e87c9235ac", user_id: 5, board_id: 7)
Pin.create!(title: "North Shore Family Escapes To Michigan Retreat", description: "North Shore Family Escapes To Michigan Retreat", image_url: "http://www.luxesource.com/Content/Slideshow/LXCH23mrFEAFRA_1_IMG_9153.jpg", url: "http://luxeworthy.luxesource.com/slideshow/151/north-shore-family-escapes-to-michigan-retrea/6", user_id: 8, board_id: 10)
Pin.create!(title: "The Northern Lights: Trip of a Lifetime", description: "Where to go to see the Northern Lights, including information on Iceland, Scandinavia, Finland and Canada, the best tour operators,…", image_url: "https://s-media-cache-ak0.pinimg.com/564x/73/4d/52/734d5239a66dcf64cb94279b81d6234c.jpg", url: "http://www.telegraph.co.uk/travel/activity-and-adventure/The-northern-lights-Trip-of-a-Lifetime/", user_id: 1, board_id: 2)
Pin.create!(title: "GARLIC CHEESE NAAN", description: "Garlic Cheese Naan is super soft and flavorful flat bread that you must not miss to try. The minced garlic and melted cheese in every single bite makes this bread simply irresistible.", image_url: "https://s-media-cache-ak0.pinimg.com/236x/11/42/2f/11422f3e5386f483594c3b17a7a82619.jpg", url: "http://www.cookwithkushi.com/garlic-cheese-naan/", user_id: 1, board_id: 1)
Pin.create!(title: "Cinnamon Sugar Mini Donuts", description: "So, this time I am going to show you something...", image_url: "https://s-media-cache-ak0.pinimg.com/564x/0e/fa/e4/0efae476cfdacb04f7056a56457936ac.jpg", url: "http://www.cookingonthefrontburners.com/2016/08/baked-cinnamon-sugar-mini-donuts-fair-style.html", user_id: 1, board_id: 1)
Pin.create!(title: "Santorini, Greece", description: "#nature photography #hdr photography", image_url: "https://s-media-cache-ak0.pinimg.com/564x/78/7f/c3/787fc31899ab88608892e46423c94617.jpg", url: "http://fullhdphotographyart.tumblr.com/post/80250655727/santorini-greece-source", user_id: 3, board_id: 5)
Pin.create!(title: "EDITORIAL: Ji Hye Park for Glamour Germany", description: "ASIAN MODELS BLOG", image_url: "https://s-media-cache-ak0.pinimg.com/564x/9c/46/7c/9c467c193b2543f7f4a66386b2823ef3.jpg", url: "http://asianmodelsblog.blogspot.ca/", user_id: 3, board_id: 5)
Pin.create!(title: "CHEZ MARIE SIXTINE", description: "Welcome to Marie Sixtine’s apartment. Located on the upper floor of the Marie Sixtine shop, rue de Charonne in the 11th district in Paris, Marie’s apartment breaks the interior design codes with a mix of pastel hues – think Rose Quartz and Serenity Blue Pantone’s colors of the year.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/e0/22/e1/e022e1a41cc471025292a6d9f058ff81.jpg", url: "http://frenchbydesignblog.com/", user_id: 4, board_id: 6)
Pin.create!(title: "20 Beautiful Bedroom Color Schemes To Choose From", description: "20 Beautiful Bedroom Color Schemes To Choose From", image_url: "https://s-media-cache-ak0.pinimg.com/564x/86/ed/88/86ed88033076456c09731da318370430.jpg", url: "http://www.homedesignetc.com/bathrooms/", user_id: 8, board_id: 10)
Pin.create!(title: "Lose Weight", description: "How to Lose Weight Without Exercise, How to Lose Weight Fast Without Exercising.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/d2/e5/c1/d2e5c1edbdd1258b94e819264cae134a.jpg", url: "https://www.youtube.com/watch?v=ITkJDrQsNKg", user_id: 6, board_id: 8)
Pin.create!(title: "Daydreaming: Outdoor Beds", description: "Daydreaming: Outdoor Beds", image_url: "https://s-media-cache-ak0.pinimg.com/564x/25/d5/c3/25d5c3a6d8bd4b2f9ccda6dc0675a41b.jpg", url: "https://centsationalgirl.com/2016/03/daydreaming-outdoor-beds/", user_id: 8, board_id: 10)
Pin.create!(title: "Student Work", description: "works", image_url: "https://s-media-cache-ak0.pinimg.com/564x/4a/e8/3b/4ae83b9be6aa6b5c336677a5b84c4cc6.jpg", url: "http://www.shillingtoncollege.com.au/graphic-design-course/student-work", user_id: 4, board_id: 6)

Pin.create!(title: "10 amazing places to see one day.", description: "Ten AMAZING jaw dropping places to see one day. Stunning one of kind locations from across the globe.", image_url: "https://s-media-cache-ak0.pinimg.com/236x/ed/4d/4f/ed4d4fb9c6fd74ef4a305ed7d21caf12.jpg", url: "http://www.gloholiday.com/10-fascinating-places-to-visit-one-day/", user_id: 1, board_id: 2)
Pin.create!(title: "Medium 3 shelf stepped design, 28mm copper pipe unit", description: "Depth 33.5 cm x Width 100 cm x Height 90 cm", image_url: "https://s-media-cache-ak0.pinimg.com/564x/3d/89/31/3d8931d4be6482b6fceaf2caeb68f72e.jpg", url: "http://steelrootsdesign.co.uk/shop/copper-furniture/medium-3-shelf-28mm-copper-pipe-unit-wall-mounted/", user_id: 8, board_id: 10)
Pin.create!(title: "Carrie Underwood", description: "C.U.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/22/e4/95/22e4954bae6c6e091a527fbef19bd041.jpg", url: "http://sissybeary.tumblr.com/post/106625612595", user_id: 2, board_id: 4)
Pin.create!(title: "Blake Lively", description: "Cosmopolitan Australia Magazine", image_url: "https://s-media-cache-ak0.pinimg.com/564x/a3/23/12/a323129e9ee820cd1d9e8a4dbc1b171b.jpg", url: "http://www.gotceleb.com/blake-lively-cosmopolitan-australia-magazine-december-2013-2013-11-23.html/blake-lively-cosmopolitan-australia-01", user_id: 2, board_id: 4)
Pin.create!(title: "Rihanna tucks into lipstick-shaped cake", description: "The new lipstick that she created in collaboration with MAC sold out just three hours after hitting shelves last week.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/73/59/f8/7359f889e54196d19d031cf1fd844cec.jpg", url: "http://www.dailymail.co.uk/tvshowbiz/article-2321220/Rihanna-tucks-lipstick-shaped-cake--RiRi-Woo-edition-MAC-sells-just-hours.html", user_id: 2, board_id: 4)
Pin.create!(title: "Palawan: The Most Beautiful Island in the World", description: "The Philippines's Palawan Island was voted the most beautiful island in the world, and with these photos, you can see why Palawan is a…", image_url: "https://s-media-cache-ak0.pinimg.com/564x/58/31/0b/58310bbb28a280c7c43dc2705133136d.jpg", url: "http://thesundaychapter.com/2016/01/palawan-the-most-beautiful-island-in-the-world/", user_id: 1, board_id: 2)
Pin.create!(title: "You Can Rent A Glass Igloo In Finland To Watch The Northern Lights", description: "Imagine looking up at the Northern Lights from a cozy hotel room 250 km above the Arctic Circle.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/76/c4/cc/76c4ccd6ec87397f36487d13ed110bd5.jpg", url: "https://www.buzzfeed.com/ryanhatesthis/you-can-rent-a-glass-igloo-in-finland-to-watch-the", user_id: 1, board_id: 2)
Pin.create!(title: "Korean Barbecue Rice Bowl", description: "Enjoy :)", image_url: "https://s-media-cache-ak0.pinimg.com/564x/39/04/62/39046232ea5142e5fb1aa237a0adbe86.jpg", url: "https://www.unclebens.com/recipesearch/korean-barbecue-rice-bowl?pp=0", user_id: 1, board_id: 1)
Pin.create!(title: "PF CHANG’S CHICKEN LETTUCE WRAPS", description: "I am such a sucker for lettuce wraps. They are so low in carbs so I become a bottomless pit, stuffing my face without any kind of guilt. And when it’s an exact PF Chang’s replica that can be made in 20 minutes or less – well, that just means I’m having this 5 times a week.", image_url: "https://s-media-cache-ak0.pinimg.com/236x/14/26/f0/1426f0a61e908e89457f041eefe218fd.jpg", url: "http://damndelicious.net/2014/05/30/pf-changs-chicken-lettuce-wraps/", user_id: 1, board_id: 1)
Pin.create!(title: "24 hours in New York City", description: "One perfect day", image_url: "https://s-media-cache-ak0.pinimg.com/564x/c1/b3/6f/c1b36f80d4bd7a5ce5bc6b85cc31c0fc.jpg", url: "https://www.lonelyplanet.com/usa/new-york-city/travel-tips-and-articles/76747", user_id: 1, board_id: 2)
Pin.create!(title: "Bora Bora Island", description: "one of the most magical and beautiful islands in the world.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/29/4e/86/294e86c24421a1afde0e8b278b7f3255.jpg", url: "http://www.topdreamer.com/bora-bora-island-most-exotic-islands/", user_id: 1, board_id: 2)
Pin.create!(title: "London", description: "London", image_url: "https://s-media-cache-ak0.pinimg.com/236x/2f/96/6c/2f966cab8d075c08b55b62d36ab9d102.jpg", url: "http://www.sacramentostreet.com/2016/03/im-loving-131/", user_id: 1, board_id: 2)
Pin.create!(title: "Cherry blossoms in Paris", description: "Cherry blossoms in Paris", image_url: "https://s-media-cache-ak0.pinimg.com/564x/f5/22/ca/f522ca16f70752c454f485c483381b4e.jpg", url: "https://plus.google.com/u/0/114596371341522095848/posts/Y1t5t4dp4ro?cfem=1", user_id: 1, board_id: 2)
Pin.create!(title: "Creamy Spinach Tomato Tortellini", description: "Wooooo.", image_url: "http://www.cookingclassy.com/wp-content/uploads/2014/06/creamy-spinach-tortellini-4edit+srgb..jpg", url: "http://www.cookingclassy.com/2014/06/creamy-spinach-tomato-tortellini/?utm_source=feedburner&utm_medium=email&utm_campaign=Feed:+CookingClassy+(Cooking+Classy)", user_id: 1, board_id: 1)
Pin.create!(title: "Classic Mint Chocolate Brownies", description: "Tasty!", image_url: "https://s-media-cache-ak0.pinimg.com/236x/e6/7e/aa/e67eaa2808d2865a903d07a94b527eed.jpg", url: "http://sallysbakingaddiction.com/2014/12/05/classic-mint-chocolate-brownies/", user_id: 1, board_id: 1)
Pin.create!(title: "Boruto and Naruto", description: "Boruto and Naruto", image_url: "https://s-media-cache-ak0.pinimg.com/564x/e2/31/44/e23144a43fff6f5f29db9586eda5086e.jpg", url: "http://tessa-sama.tumblr.com/post/126008922911/boruto-and-naruto", user_id: 5, board_id: 7)
Pin.create!(title: "32 Stunning Patio Outdoor Lighting Ideas", description: "Looking to for outdoor lighting, outdoor lights, patio lights & garden lights? Access our photo gallery from top outdoor designers and get", image_url: "https://s-media-cache-ak0.pinimg.com/564x/a2/4d/7c/a24d7c1b210b67d86b0f6f57ba742962.jpg", url: "http://www.homedesignetc.com/stunning-patio-lighting/", user_id: 8, board_id: 10)
Pin.create!(title: "Zac Efron", description: "On Fire!!", image_url: "https://s-media-cache-ak0.pinimg.com/564x/8b/04/b8/8b04b896e2eb6dab9b8f6564c4c8fa68.jpg", url: "http://www.listal.com/viewimage/1297036", user_id: 2, board_id: 4)
Pin.create!(title: "Sam Claflin", description: "Sam oh Sam", image_url: "https://s-media-cache-ak0.pinimg.com/564x/ad/3b/bc/ad3bbc5b926731de09e247f52fe5bc3a.jpg", url: "http://www.tumblr.com/likes/page/17", user_id: 2, board_id: 4)
Pin.create!(title: "Streets of Monaco at Night", description: "This is the place!", image_url: "https://s-media-cache-ak0.pinimg.com/236x/92/79/74/9279748d7ef58e102bab2b612e1d251e.jpg", url: "http://www.entouriste.com/hills-of-monaco/streets-of-monaco-at-night/", user_id: 1, board_id: 2)
Pin.create!(title: "Zip Line in Alps", description: "Pretty fun!", image_url: "https://s-media-cache-ak0.pinimg.com/236x/d7/eb/94/d7eb94c77bf9e9b2d79735fd07edf59a.jpg", url: "http://www.ladylux.com/articles/9-bucket-list-travel-spots", user_id: 1, board_id: 2)

Pin.create!(title: "The Two Minute Cinnamon Banana Mug Cake", description: "I highly suggest you take two minutes to whip this up and try it out for yourself! You will be happy you did.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/e7/a8/94/e7a894db218c1f03674906a5d378621c.jpg", url: "http://www.delightedmomma.com/2013/09/the-two-minute-cinnamon-banana-mug-cake.html?m=1", user_id: 1, board_id: 1)
Pin.create!(title: "Key Deer", description: "Deer", image_url: "https://s-media-cache-ak0.pinimg.com/564x/b4/4b/ad/b44bad93c6c4205c1aaf2719ad93db5b.jpg", url: "https://www.flickr.com/photos/kygirl/3719252610/in/set-72157625189533371", user_id: 2, board_id: 3)
Pin.create!(title: "Bear cub", description: "Cute!!", image_url: "https://s-media-cache-ak0.pinimg.com/564x/37/35/10/373510e6422dc7e01d281647116f3731.jpg", url: "http://imgfave.com/view/4179679?r=pin", user_id: 2, board_id: 3)
Pin.create!(title: "Karen Thorell", description: "Fly away!", image_url: "https://s-media-cache-ak0.pinimg.com/236x/48/8f/c4/488fc4ed638ecbb2c04994c3ecaf36dc.jpg", url: "http://urbanpeek.com/2013/04/24/picture-of-the-day-first-flight/", user_id: 2, board_id: 3)
Pin.create!(title: "Thanks mom.", description: "Love", image_url: "https://s-media-cache-ak0.pinimg.com/236x/8b/8c/3c/8b8c3c028bb80a82b4c0a3d93e9814b4.jpg", url: "http://media-cache-ak0.pinimg.com/640x/84/fe/b0/84feb014350453defe5331d07b6a70e8.jpg", user_id: 2, board_id: 3)


Pin.create!(title: "Charize Theron", description: "So pretty.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/06/a6/0d/06a60d00ef01eac579ad71b9ce72a733.jpg", url: "http://sickatunde.tumblr.com/post/17264141974", user_id: 2, board_id: 4)
Pin.create!(title: "Ari", description: "Dangerous Woman", image_url: "https://s-media-cache-ak0.pinimg.com/564x/99/48/3b/99483b369c43cf291a14f42cf046c813.jpg", url: "http://arianagrante.tumblr.com/post/144394710584", user_id: 2, board_id: 4)
Pin.create!(title: "Tiaras at dawn", description: "No one doubts that Prince William and Kate Middleton have strong views about what their wedding should be like. ", image_url: "https://s-media-cache-ak0.pinimg.com/564x/11/ee/1b/11ee1be24787f41ec81d8b9fab99d727.jpg", url: "http://www.dailymail.co.uk/femail/article-1374244/Royal-Wedding-Kate-Middelton-Prince-William-clash-Charles-Camilla-tiaras.html", user_id: 2, board_id: 4)
Pin.create!(title: "7 Things You Didn't Know About Jennifer Lawrence", description: "With all the Catching Fire news going around, you're probably pretty familiar with the movie's lead, Jennifer Lawrence.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/44/b5/fb/44b5fbc94833879728a1e3d19b830453.jpg", url: "http://www.hercampus.com/entertainment/7-things-you-didnt-know-about-jennifer-lawrence", user_id: 2, board_id: 4)
Pin.create!(title: "New Born", description: "kitten", image_url: "https://s-media-cache-ak0.pinimg.com/236x/ef/3b/0d/ef3b0d80401a61e9dab4bd6dbe2477e2.jpg", url: "http://www.sparkpeople.com/mypage_public_journal_individual.asp?blog_id=6014213", user_id: 2, board_id: 3)
Pin.create!(title: "Classy", description: "Now you see me.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/7a/ae/92/7aae92e618dcbc052a079315cd41bbfc.jpg", url: "http://modernandclassy.tumblr.com/post/66217048395", user_id: 2, board_id: 3)
Pin.create!(title: "Cat always improvises...", description: "Cat", image_url: "https://s-media-cache-ak0.pinimg.com/236x/44/be/d2/44bed2089c93eeee515b7567ba40d495.jpg", url: "http://www.topontiki.gr/article/125892/ta-katoikidia-koimoyntai-sta-pio-apithana-meri-14-apisteytes-fotografies-photos#.VTYVklDDScY.facebook", user_id: 2, board_id: 3)
Pin.create!(title: "Rosie Huntinton", description: "After the Oscars", image_url: "", url: "http://wwd.com/eye/parties/gallery/aaaaaand-scene-stars-party-after-the-oscars/", user_id: 2, board_id: 4)
Pin.create!(title: "Emma Stone", description: "Oh, REDHEAD Emma Stone is my new girl crush!", image_url: "https://s-media-cache-ak0.pinimg.com/564x/5a/75/2e/5a752ebb4eb862fcb3290a9f4e027c36.jpg", url: "http://for-redheads.tumblr.com/post/14198183829/redheadmermaid-oh-redhead-emma-stone-is-my", user_id: 2, board_id: 4)

Pin.create!(title: "Petirrojo", description: "Petirrojo", image_url: "https://s-media-cache-ak0.pinimg.com/564x/a4/a2/fa/a4a2fae120f7d305ae74956b1acc2280.jpg", url: "https://500px.com/photo/51843758/petirrojo-by-cesar-pastor-quesada", user_id: 3, board_id: 5)
Pin.create!(title: "AKAPEARLOFAGIRL", description: "Whatever happens at tumblr, stays at tumblr.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/4b/68/5b/4b685be142d69256c056077c97eb5e98.jpg", url: "http://akapearlofagirl.tumblr.com/post/64969436294/chrystalines75-osprey", user_id: 3, board_id: 5)
Pin.create!(title: "5 Reasons Why Everyone Should Visit Paris", description: "If for no other reason, Paris should be visited at least once because of the sheer variety of experiences that you can enjoy during a trip...", image_url: "https://s-media-cache-ak0.pinimg.com/564x/c6/bb/df/c6bbdf69727f1e855a3d3c90e8ecb496.jpg", url: "http://www.99traveltips.com/travel-tips/5-reasons-why-everyone-should-visit-paris/", user_id: 3, board_id: 5)
Pin.create!(title: "Golden love", description: "Golden love", image_url: "https://s-media-cache-ak0.pinimg.com/564x/e8/3b/c4/e83bc4ab4d58f5b5583bcc14aab427be.jpg", url: "http://www.playbuzz.com/barkpost10/whats-your-dog-naming-style", user_id: 2, board_id: 3)
Pin.create!(title: "No wake zone", description: "No wake zone - great piece of art for a lake house , beach house or a bedroom- plank style vintage sign", image_url: "https://s-media-cache-ak0.pinimg.com/564x/94/c1/3a/94c13a801fa858666d5229bef3535a57.jpg", url: "https://www.etsy.com/listing/159530997/no-wake-zone-great-piece-of-art-for-a", user_id: 8, board_id: 10)
Pin.create!(title: "YOU CAN NEVER BE TOO OLD! ANIMATED MOVIES WE LOVE AS ADULTS", description: "UP 3D", image_url: "https://s-media-cache-ak0.pinimg.com/564x/71/fc/1f/71fc1f0863d20c99731a07e53b3adec9.jpg", url: "http://madamenoire.com/283787/you-can-never-be-too-old-animated-movies-we-love-as-adults/12/", user_id: 5, board_id: 7)
Pin.create!(title: "IN BROOKLYN, THE HOME OF JONATHAN ADLER’S DIRECTOR OF INTERIORS", description: "Benjamin proudly stands by the products he works with at Jonathan Adler and used them to decorate his living room. From lighting and chairs to decor, the brand can be seen in all of the space's corners.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/ce/4a/fe/ce4afec0640166d0be483ecc86f63e01.jpg", url: "http://www.designsponge.com/2016/08/in-brooklyn-the-home-of-jonathan-adlers-director-of-interiors.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+designsponge/njjl+(Design*Sponge)", user_id: 8, board_id: 10)
Pin.create!(title: "typescreen ipad", description: "If you are looking for a more old school way to type, check out the new Typescreen from Spinning Hat. It’s a typewriter style keyboard dock for the iPad and iPad 2 that allows you get all retro and actually type as if using a typewriter.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/8c/c5/2f/8cc52fc881a7ebfa70f3195bb289f6e8.jpg", url: "http://www.slipperybrick.com/search/typescreen%20ipad", user_id: 7, board_id: 9)
Pin.create!(title: "Love in Paris", description: "Pinlovely.com", image_url: "https://s-media-cache-ak0.pinimg.com/564x/2a/4e/b1/2a4eb11283aab688fce06f851ffa57b1.jpg", url: "http://pinlovely.com/seasons-hotel-george-v-paris-france/", user_id: 3, board_id: 5)
Pin.create!(title: "Newborn Photography Pose Guide", description: "For anyone who photographs newborns, getting the right pose can make the difference between good and great. Posing with newborns can be a...", image_url: "https://s-media-cache-ak0.pinimg.com/564x/f9/e6/6d/f9e66d8167ed3dbe4cf46d7ecc452bb3.jpg", url: "http://photographypla.net/newborn-pose-guide/", user_id: 3, board_id: 5)
Pin.create!(title: "Bed", description: "brooklinen", image_url: "https://s-media-cache-ak0.pinimg.com/564x/52/3c/e7/523ce720c48238221d3151cef70f3159.jpg", url: "https://www.brooklinen.com/?utm_source=pinterest&utm_medium=cpc&utm_campaign=cpc-2016-US-ALL-newlywedsKW-headoverheals&pp=0", user_id: 3, board_id: 5)

Pin.create!(title: "Enjoy the little things", description: "A Halloween look that will NOT give you the creeps… BOO!", image_url: "https://s-media-cache-ak0.pinimg.com/564x/3d/a7/62/3da762ce950eac5d5eff1ba0dfc0b7bc.jpg", url: "http://enjoythelittlethings.pl/a-halloween-look-that-will-not-give-you-the-creeps-boo/", user_id: 4, board_id: 6)
Pin.create!(title: "Nadal Out Of U.S. Open", description: "Nadal Out Of U.S. Open After Upset Loss To France’s Pouille", image_url: "https://s-media-cache-ak0.pinimg.com/564x/8b/5e/0d/8b5e0db33e80270753f42d009372ae21.jpg", url: "http://www.huffingtonpost.com/entry/nadal-out-of-us-open-after-upset-loss-to-frances-pouille_us_57ccca3ce4b0e60d31df9890", user_id: 6, board_id: 8)
Pin.create!(title: "The Martian", description: "Genre: Adventure, Drama, Sci-Fi", image_url: "https://s-media-cache-ak0.pinimg.com/564x/e5/52/02/e5520252b03ada02c6eb3f004a38b135.jpg", url: "http://megashare.live/watch-the-martian-online-free-778651008.html", user_id: 5, board_id: 7)
Pin.create!(title: "Drone buying guide", description: "How to choose the right drone for fun or business", image_url: "https://s-media-cache-ak0.pinimg.com/564x/83/05/e9/8305e900fa0bde56101b32a00be5f6cc.jpg", url: "http://www.crutchfield.com/S-WY1iXtWcPd5/learn/drone-buying-guide.html?xvver=C75&pp=0", user_id: 7, board_id: 9)
Pin.create!(title: "Shakespeare Wedding Day Evokes Passion and Love", description: "A Shakespeare wedding day evokes the ideas of adventurous passion, heightened love and a marriage of true minds.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/6a/60/bc/6a60bc021b66a13214e9a8f412ceecfc.jpg", url: "http://strictlyweddings.com/blog/2015/11/shakespeare-wedding/", user_id: 3, board_id: 5)
Pin.create!(title: "Ski", description: "Ski", image_url: "https://s-media-cache-ak0.pinimg.com/564x/95/c9/c9/95c9c934ef5c115a8ce21fe94f6c7cf1.jpg", url: "http://03633610.tumblr.com/post/76630592798", user_id: 6, board_id: 8)
Pin.create!(title: "Superman", description: "Colored with Photoshop CS6 and a Wacom Intuos pro.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/ff/53/e1/ff53e1e7f9710feb3f66b9c180fd5086.jpg", url: "http://brianskipper.deviantart.com/art/Superman-630179859", user_id: 5, board_id: 7)
Pin.create!(title: "The spy", description: "added grip", image_url: "https://s-media-cache-ak0.pinimg.com/564x/aa/a0/b6/aaa0b605a9c47a4ab01a5a3e9fdabfb9.jpg", url: "https://www.totalleecase.com/products/clear-iphone-case?pp=0", user_id: 4, board_id: 6)
Pin.create!(title: "samurai", description: "samurai", image_url: "https://s-media-cache-ak0.pinimg.com/564x/f6/a2/6e/f6a26e3da1a60cc115afa06bf1bde7f8.jpg", url: "http://kgthunder.tumblr.com/image/29787107964", user_id: 4, board_id: 6)
Pin.create!(title: "The Secret Ancient City of Bagan, Myanmar", description: "Let's go!", image_url: "https://s-media-cache-ak0.pinimg.com/564x/3c/0f/3c/3c0f3c9c936da47772b912844a475f90.jpg", url: "http://thesundaychapter.com/2016/03/the-ancient-city-of-bagan-myanmar/", user_id: 1, board_id: 2)
Pin.create!(title: "EASY HOMEMADE WONTON SOUP RECIPE", description: "This authentic homemade wonton soup recipe is easy and fun to make! Each hearty bowl is packed with plump pork dumplings, fresh vegetables and jumbo shrimp.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/f5/77/cc/f577ccda79c3b8b15b0487e9f9dddbfa.jpg", url: "http://www.jessicagavin.com/wonton-soup-recipe-thats-easy-to-make/", user_id: 1, board_id: 1)
Pin.create!(title: "Chris Pine", description: "Chris", image_url: "http://indulgy.com/post/o1lrBJC4F2/chris-pine-c-magazing", url: "http://indulgy.com/post/o1lrBJC4F2/chris-pine-c-magazing", user_id: 2, board_id: 4)
Pin.create!(title: "Ryan Gosling", description: "imdb", image_url: "https://s-media-cache-ak0.pinimg.com/564x/8a/3a/cf/8a3acf4ed127c424374145db00e00b3e.jpg", url: "http://www.imdb.com/name/nm0331516/", user_id: 2, board_id: 4)
Pin.create!(title: "Hot Sausage Buffalo Dip", description: "Now that the holidays are over we can get back to focusing on football. The first playoff games in college football were played yesterday. There is one more game to determine the champion. The NFL is getting ready for the playoffs. There is still a lot of tailgating to be done!", image_url: "http://2.bp.blogspot.com/-f6rN3XfUzeg/VHpvP0qx1TI/AAAAAAAAcg8/8yq6yrwjz08/s1600/hot%2Bsausage%2Bbuffalo%2Bdip%2B(6)A.jpg", url: "http://www.plainchicken.com/2015/01/hot-sausage-buffalo-dip-football-friday.html", user_id: 1, board_id: 1)
Pin.create!(title: "Panera Bread Broccoli Cheddar Soup Copycat Recipe", description: "This is exactly like Panera Bread's broccoli soup. It is so thick, rich, creamy, and cheesy.", image_url: "http://3.bp.blogspot.com/-8UOCQWEhdc8/Up-2Tv1aiYI/AAAAAAAAIUs/sGpBj2vIeFQ/s640/DSC_0644.tiff", url: "http://www.yammiesnoshery.com/2013/12/panera-bread-broccoli-cheddar-soup.html", user_id: 1, board_id: 1)
Pin.create!(title: "House in Kawasaki par Taichi Mitsuya & Associates", description: "House in Kawasaki", image_url: "https://s-media-cache-ak0.pinimg.com/564x/ad/46/c2/ad46c2000fff698e2f34694e6a0580ae.jpg", url: "http://www.journal-du-design.fr/architecture/house-kawasaki-par-taichi-mitsuya-associates-66890/", user_id: 8, board_id: 10)
Pin.create!(title: "Iowa City farmhouse", description: "Iowa City farmhouse blends with tradition with cozy comfort", image_url: "https://s-media-cache-ak0.pinimg.com/564x/c9/1e/b4/c91eb4756adf76f0f5dd5b33474630ed.jpg", url: "http://farmhouse.countryhometours.com/2016/07/03/iowa-city-farmhouse-blends-with-tradition-with-cozy-comfort/?src=fbfan_53378&t=fbsub_countryhometours", user_id: 8, board_id: 10)
Pin.create!(title: "Bring on the Fall Decor! 18 DIYs to Get Ready for Fall", description: "Bring on the Fall Decor! 18 DIYs to Get Ready for Fall", image_url: "https://s-media-cache-ak0.pinimg.com/564x/ca/6d/78/ca6d78e97abf684207c3630cc7204257.jpg", url: "http://howdoesshe.com/bring-on-the-fall-decor-18-diys-to-get-ready-for-fall/", user_id: 8, board_id: 10)
Pin.create!(title: "Curry", description: "30 Of The Absolute Cutest Riley Curry Moments", image_url: "https://s-media-cache-ak0.pinimg.com/564x/16/d8/64/16d86456386d70739ae8a182b457b833.jpg", url: "https://www.buzzfeed.com/jessicamisener/riley-curry-2016", user_id: 6, board_id: 8)
Pin.create!(title: "YOGA ROUTINE IN THE MORNING", description: "YOGA", image_url: "https://s-media-cache-ak0.pinimg.com/564x/60/76/fd/6076fd023addf36a9b1cb9a8c9e86e64.jpg", url: "http://healthinpics.blogspot.com/2012/12/yoga-routine-in-morning.html", user_id: 6, board_id: 8)
Pin.create!(title: "FC Barcelona v Club Atletico de Madrid - La Liga", description: "Lionel Messi of FC Barcelona runs with the ball during the La Liga match between FC Barcelona and Club Atletico de Madrid at Camp Nou on January 11, 2015 in Barcelona, Spain.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/da/a1/72/daa172abd77510dbccaf1c77ab6a7502.jpg", url: "http://www.zimbio.com/pictures/7eab-zOCHB8/FC+Barcelona+v+Club+Atletico+de+Madrid+La/oQq2rZNcLNL", user_id: 6, board_id: 8)
Pin.create!(title: "York Lounge Chair", description: "Cozy", image_url: "https://s-media-cache-ak0.pinimg.com/564x/f5/ca/df/f5cadf03fd1c5c9840be2e2fcc898e1e.jpg", url: "http://modloft.com/store/Lounge-Chairs/York-Lounge-Chair?utm_source=pinterest&utm_medium=cpc&utm_term=promoted&utm_content=branded&utm_campaign=ppins&pp=0", user_id: 4, board_id: 6)
Pin.create!(title: "Side By Side Wine Coolers", description: "Amazing kitchen features a built-in glass-front china cabinet situated next to side by side glass-door wine coolers atop a black staggered tiled floor.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/f0/65/25/f06525cd9125ca02b61c41d1304eb44d.jpg", url: "https://www.decorpad.com/photo.htm?photoId=126822", user_id: 4, board_id: 6)
Pin.create!(title: "Stand for Macbook", description: "Product Design", image_url: "https://s-media-cache-ak0.pinimg.com/564x/40/a5/fc/40a5fc1e9cae5250657b5e9c871c8866.jpg", url: "https://www.behance.net/gallery/Stand-for-Macbook/10218303", user_id: 4, board_id: 6)
Pin.create!(title: "Lihi Hod Bridal 2016 Wedding Dresses", description: "Today we have some really stunning eye candy courtesy of Lihi Hod’s 2016 bridal collection.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/fb/7a/cb/fb7acb05826330e7b7c74bf507cd9f7f.jpg", url: "http://www.weddinginspirasi.com/2015/12/22/lihi-hod-bridal-2016-wedding-dresses/", user_id: 4, board_id: 6)

Pin.create!(title: "Bookbub", description: "Bookbub", image_url: "https://s-media-cache-ak0.pinimg.com/564x/b8/28/a4/b828a401bccedbf25641c9a8e582d7ca.jpg", url: "http://landers.bookbub.com/covers/?source=pintad_general_kwint_need2know_plainstanding&pp=0", user_id: 5, board_id: 7)
Pin.create!(title: "Shop style", description: "Shop style", image_url: "https://s-media-cache-ak0.pinimg.com/564x/f4/e8/1e/f4e81e15b7294e958ce378aef73e6f17.jpg", url: "http://www.neimanmarcus.com/Shoes/Categories/Shop-All-Shoes/cat47190746_cat13030734_cat000141/c.cat?icid=error_Shoe", user_id: 5, board_id: 7)
Pin.create!(title: "Tian Yi", description: "Model", image_url: "https://s-media-cache-ak0.pinimg.com/564x/ef/92/bf/ef92bf507bcf4f434330c1ed656b0ab3.jpg", url: "http://ww12.stormtrooperfashion.com/", user_id: 3, board_id: 5)
Pin.create!(title: "Lady Mer", description: "eliapan", image_url: "https://s-media-cache-ak0.pinimg.com/564x/2d/f1/7e/2df17e4fe92d1a470b4ff0eb23c7a1b7.jpg", url: "http://hellotimandra47universe.tumblr.com/post/116294496870", user_id: 3, board_id: 5)
Pin.create!(title: "THE MUSICIAN MUG", description: "mug", image_url: "https://s-media-cache-ak0.pinimg.com/564x/45/f6/2f/45f62f4af10063f2e66f8b1134fddfb2.jpg", url: "http://www.cafepress.com/mf/29600626/the-musician_mugs?productId=295491597", user_id: 5, board_id: 7)
Pin.create!(title: "Game of Thrones", description: "Game of Thrones season 4 finale 'The Children', review: A fitting end", image_url: "https://s-media-cache-ak0.pinimg.com/564x/16/17/20/16172043b57528ac0557e78c3ab7f754.jpg", url: "http://www.independent.co.uk/arts-entertainment/tv/reviews/game-of-thrones-season-4-finale-review-a-fitting-end-to-the-most-tumultuous-season-yet-9537245.html", user_id: 5, board_id: 7)
Pin.create!(title: "Titanic", description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/12/d5/ba/12d5baa2d2a9ba2b0cb47fd7c30d7479.jpg", url: "http://m.imdb.com/title/tt0120338/mediaindex?photoId=MV5BMjI4OTQxNDYxNV5BMl5BanBnXkFtZTcwMDM3NTk1Nw", user_id: 5, board_id: 7)
Pin.create!(title: "45 iconic fashion films", description: "Stylist magazine look at the most iconic fashion moments in film and the stories behind every one, from costume designers to interesting...", image_url: "https://s-media-cache-ak0.pinimg.com/564x/87/dd/1c/87dd1c32eed6a010596f02027c85d075.jpg", url: "http://www.stylist.co.uk/fashion/45-iconic-fashion-films", user_id: 5, board_id: 7)

Pin.create!(title: "Brandon Crawford", description: "SF Giants", image_url: "https://s-media-cache-ak0.pinimg.com/564x/ae/2b/9a/ae2b9a5ba761ecf0a90ea419859607b2.jpg", url: "http://www.espn.com/mlb/team/photos/_/name/ari/photoId/4683372/arizona-diamondbacks", user_id: 6, board_id: 8)
Pin.create!(title: "Andy Murray", description: "Andy Murray Kept Brother Jamie Rivalry Out Of Relationship With WIfe Kim Sears", image_url: "https://s-media-cache-ak0.pinimg.com/564x/25/63/1f/25631fdcfb15a91c1ecb589c5ce4c440.jpg", url: "http://www.kpopstarz.com/articles/251349/20151025/andy-murray-brother-jamie-rivalry-wife-kim-sears.htm", user_id: 6, board_id: 8)
Pin.create!(title: "Kylie Jenner's Secrets", description: "What's style?", image_url: "https://s-media-cache-ak0.pinimg.com/564x/88/ee/1f/88ee1f96872f3c1b992dfebef0478fef.jpg", url: "https://www.style.com/", user_id: 4, board_id: 6)
Pin.create!(title: "FIBERGLASS DINING TABLE", description: "Dining tables.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/05/09/ab/0509ab8bd7e0471dc87d37a6f9913a01.jpg", url: "http://www.lexmod.com/c-225-dining-tables.aspx?utm_source=pinterest&utm_medium=cpc&utm_campaign=ROI+Desktop+Lippa+Table+Text&pp=0", user_id: 4, board_id: 6)
Pin.create!(title: "Workspace in soft neutral tones", description: "Workspace in soft neutral tones", image_url: "https://s-media-cache-ak0.pinimg.com/564x/90/0a/2f/900a2feb8c54e93bfa29cbee96f13009.jpg", url: "https://www.bloglovin.com/blogs/daily-dream-decor-2331986/workspace-in-soft-neutral-tones-4251880099", user_id: 8, board_id: 10)
Pin.create!(title: "Marshawn Lynch", description: "Marshawn Lynch Spotlight Seattle Seahawks", image_url: "https://s-media-cache-ak0.pinimg.com/564x/2e/be/90/2ebe90e5287b4c2d2a1b9e3f9ec40240.jpg", url: "http://www.bestsportsphotos.com/products/marshawn-lynch-spotlight-seattle-seahawks-satin-8x10-photo", user_id: 6, board_id: 8)


Pin.create!(title: "tempered glass iphone screen protector", description: "tempered glass iphone screen protector", image_url: "https://s-media-cache-ak0.pinimg.com/564x/7f/b6/bb/7fb6bbad57a8f25c1c1fce6b9ffe04ed.jpg", url: "https://www.totalleecase.com/products/iphone-glass-screen-protector?pp=0", user_id: 7, board_id: 9)
Pin.create!(title: "Forever 23", description: "#Kobe #Jordan", image_url: "https://s-media-cache-ak0.pinimg.com/564x/a2/3f/fc/a23ffc3d5faffbce01d1eac51bc31bdc.jpg", url: "http://funktionality.tumblr.com/post/19631969108/mj-23-kb-24", user_id: 6, board_id: 8)
Pin.create!(title: "Surf", description: "HIGH ENOUGH TO SEE THE SEA", image_url: "https://s-media-cache-ak0.pinimg.com/564x/82/4a/55/824a5587d7440b543f5e5b70d57f64ea.jpg", url: "http://highenoughtoseethesea.tumblr.com/post/56889916929", user_id: 6, board_id: 8)
Pin.create!(title: "Alex Morgan", description: "E!Q in 42 Olympics Edition: 9 Things to Know About Alex Morgan", image_url: "https://s-media-cache-ak0.pinimg.com/564x/55/8d/fa/558dfa9fa046f35e4f33acfec802a831.jpg", url: "http://www.eonline.com/news/785654/team-usa-soccer-star-alex-morgan-takes-the-e-q-in-42-9-things-to-know-about-the-olympic-gold-medalist", user_id: 6, board_id: 8)
Pin.create!(title: "The Shade Store", description: "The Shade Store", image_url: "https://s-media-cache-ak0.pinimg.com/564x/ea/ff/b4/eaffb4cbc85fe8c87dd8e6f8bde24ef7.jpg", url: "https://www.theshadestore.com/swatches?utm_source=pinterest&utm_medium=social&utm_content=swatch-challenger-q2&utm_campaign=paid-generic-web&pp=0", user_id: 8, board_id: 10)
Pin.create!(title: "HAL Robot Suit By Cyberdyne Has Got International Safety Approval", description: "The HAL robotic suit, produced by Cyberdyne, and available for rent in Japan, has finally got an international safety approval.", image_url: "https://s-media-cache-ak0.pinimg.com/564x/a6/1f/28/a61f28e3831399debc214e0b3bf76664.jpg", url: "http://futuristicnews.com/hal-robotic-suit-by-cyberdyne-has-got-international-safety-approval/", user_id: 7, board_id: 9)
Pin.create!(title: "Social Media image size", description: "The Ultimate Cheat Sheet of Photo & Image Sizes on Facebook, Twitter, LinkedIn & Other Social Networks ", image_url: "https://s-media-cache-ak0.pinimg.com/564x/db/8f/61/db8f6175b95f4a6322fdd0f962fdf1c0.jpg", url: "http://blog.hubspot.com/marketing/ultimate-guide-social-media-image-dimensions-infographic", user_id: 7, board_id: 9)
Pin.create!(title: "Train", description: "“We travel, some of us forever, to seek other states, other lives, other souls.” - 1 Voyager", image_url: "https://s-media-cache-ak0.pinimg.com/564x/38/ea/73/38ea73fcda42bcb383dede5e9cb8d2b2.jpg", url: "http://intothegreatunknown.tumblr.com/post/41866111762/by-drewhalv", user_id: 7, board_id: 9)
Pin.create!(title: "Drone", description: "Flying around with my Syma X5SW Drone 19", image_url: "https://s-media-cache-ak0.pinimg.com/564x/b6/fe/cf/b6fecf47e1a2acd29d6935c387b1fdf1.jpg", url: "https://www.youtube.com/watch?v=9Rx7JAiNAaY&feature=youtu.be", user_id: 7, board_id: 9)
Pin.create!(title: "Laser Projected Virtual Keyboard", description: "Cool Gadgets for Geeks and Travelers This Christmas, Many of Them Bargains Under $20", image_url: "https://s-media-cache-ak0.pinimg.com/564x/5b/86/42/5b8642017d86249acf32e98f066d1d97.jpg", url: "https://wizzley.com/cool-gadgets-for-geeks-and-travelers-this-christmas-many-of-them-bargains-under-20/", user_id: 7, board_id: 9)
Pin.create!(title: "This Electric Skateboard Can Dominate Any Terrain", description: "In the works for seven years, the Scarpar is a one-man vehicle built to conquer any terrain. Why did it take so long, and will it shake up...", image_url: "https://s-media-cache-ak0.pinimg.com/564x/5a/5c/3f/5a5c3ff8cad3322a8cc6b22eea7abd13.jpg", url: "http://mashable.com/2013/07/17/scarpar/#CzhwYylhUGqn", user_id: 7, board_id: 9)
Pin.create!(title: "Zero Personal Helicopter", description: "Zero Personal Helicopter", image_url: "https://s-media-cache-ak0.pinimg.com/564x/79/a0/03/79a00396451d7fe283ddba85037ffb0b.jpg", url: "http://www.arch2o.com/zero-personal-helicopter-hector-del-amo/", user_id: 7, board_id: 9)
Pin.create!(title: "A $30,000 WATERBED THAT VIBRATES WITH MUSIC", description: "A $30,000 WATERBED THAT VIBRATES WITH MUSIC", image_url: "https://s-media-cache-ak0.pinimg.com/564x/dd/09/00/dd0900c317de9f4f0b6ccb34a8e4ef70.jpg", url: "http://www.wired.com/2014/02/tranquility-pod/", user_id: 7, board_id: 9)
